### PR TITLE
Platform Fix

### PR DESCRIPTION
**Pull request by joshgarde**

### CODE REVIEW

**Comment by piranna** [comment]
Since it doesn't matter what version of Node.js is being used on the system to build it, we should only check against one of them to speed up things... There's no need to build them twice.

**Comment by joshgarde** [comment]
The filename in releases has to be updated to darwin-x64.tar.gz

**Comment by piranna** [comment]
> The filename in releases has to be updated to darwin-x64.tar.gz

Done.

**Comment by joshgarde** [comment]
Can we have this merged?

**Comment by piranna** [comment]
Merged :-) Don't know if we should remove SemaphoreCI or left it during some time doing the tests in parallel with TravisCI...

**Pull request merged**
